export default [
    {
        id: 1,
        img: "images/phong-x-quang-dana-dental-1280x640.jpg",
        service: "Trồng Răng Implant",
        title: "CT Cone Beam 3D – Tiêu chuẩn của một Nha khoa Kỹ thuật cao",
        discrip: "Y học nói chung và nha khoa nói riêng đã có những bước phát triển vượt bậc nhờ sự hỗ trợ của khoa học công nghệ, ứng dụng máy móc hiện đại trong chẩn đoán và điều trị. Hiện nay, máy chụp CT Cone Beam tạo ra hình ảnh 3D về cấu trúc răng, mô...",
        link:"BlogBocRangSuBlog1",
        tab: "t1"
    },
    {
        id: 2,
        img: "images/trong-rang-implant.jpg",
        service: "Trồng Răng Implant",
        title: "Sau khi nhổ răng bao lâu thì trồng Implant được?",
        discrip: "Khi đến với Nha khoa trong tình trạng bị sâu nặng, viêm tủy, hoặc mất một, hai hoặc nhiều răng thì các bác sĩ của chúng tôi luôn khuyến cáo bạn sử dụng phương pháp trồng răng implant để khôi phục chức năng ăn nhai và thẩm mỹ. Vậy sau khi nhổ răng bao lâu...",
        link: "BlogBocRangSuBlog2",
        tab: "t1"
    },
    {
        id: 3,
        img: "images/Nieng-rang-zenyum-co-tot-khong-Nieng-rang-trong-suot-1280x640.jpg",
        service: "Niềng Răng ",
        title: "Niềng răng trong suốt Zenyum là gì? Có tốt không?",
        discrip: "Niềng răng trong suốt Zenyum là kỹ thuật chỉnh nha hiện đại với nhiều ưu điểm vượt trội về tính thẩm mỹ và sự tiện lợi nên được nhiều người tin tưởng lựa chọn. Vì thế niềng răng zenyum gì? Ưu và nhược điểm của niềng răng trong suốt Zenyum là gì? Quy trình thực...",
        link: "BlogNiengRangBlog1",
        tab: "t2",
    },
    {
        id: 4,
        img: "images/CAC-BUOC-CUA-QUY-TRINH-Boc-rang-su-VENEER-HOAN-2.png",
        service: "Mặt Dán Sứ",
        title: "Các bước của quy trình làm mặt dán sứ Veneer tiêu chuẩn",
        discrip: "Nếu bạn đang tìm cho mình một dịch vụ làm răng sứ thẩm mỹ không cần phải mài thân răng quá nhiều mà vẫn đảm bảo chức năng ăn nhai cũng như tính thẩm mỹ cho răng thì Veneer là phương pháp thẩm mỹ răng tốt nhất dành cho bạn. Trong bài viết này, Nha...",
        link: "BlogDanMatSuBlog1",
        tab: "t2",
    },
    {
        id: 5,
        img: "images/rang-toan-su.jpg",
        service: "Bọc Răng Sứ",
        title: "Khắc phục tình trạng đen viền nướu sau khi bọc răng sứ",
        discrip: "Bọc răng sứ được coi là phương pháp xuất hiện từ rất sớm. Phương pháp giúp khắc phục tình trạng răng bị mẻ, thưa, nhiễm màu kháng sinh nặng. Sau khi phục hình, răng mới sẽ trắng bóng tự nhiên. Tuy nhiên, thông tin về trường hợp bọc răng sứ bị đen viền nướu lại...",
        link: "BlogBocRangSuBlog1",
        tab: "t3",
    },
    {
        id: 6,
        img: "images/Rang-khon-moc-o-dau-Tai-sao-nen-nho-bo.jpg",
        service: "Nhổ Răng",
        title: "Nên nhổ bỏ răng khôn khi nào?",
        discrip: "Đau răng khôn luôn là vấn đề mà nhiều người gặp phải. Trong trường hợp này, các nha sĩ luôn khuyên chúng ta nên nhổ bỏ răng khôn để giải quyết tình trạng này. Vậy tại sao phải nhổ răng khôn? Hãy cùng Nha khoa Dana tìm hiểu trong bài viết này nhé! Răng khôn...",
        link: "BlogNhoRangBlog1",
        tab: "t3",
    },
    {
        id: 7,
        img: "images/rang-su-tham-my.jpg",
        service: "Hàn - Trám Răng",
        title: "Những thông tin về Trám răng thẩm mỹ mà bạn nên biết",
        discrip: "Trám răng thẩm mỹ là một phương pháp giúp phục hình răng được sử dụng rất phổ biến hiện nay. Tuy phổ biến nhưng có rất nhiều người vẫn chưa hiểu rõ phương pháp này. Cùng Nha Khoa Dental tìm hiểu về trám răng thẩm mỹ trong bài viết kỳ này nhé!",
        link: "BlogHanTramRangBlog1",
        tab: "t4",
    },
    {
        id: 8,
        img: "images/tay-trang-rang-tham-my-tai-da-nang.jpg",
        service: "Tẩy Trắng Răng",
        title: "Địa chỉ Tẩy trắng răng an toàn, uy tín",
        discrip: "Tẩy trắng răng giá bao nhiêu tiền? Giá thành tẩy trắng răng có đi kèm với chất lượng dịch vụ tốt? Đó có lẽ là những điều mà khách hàng tại TP Đà Nẵng băn khoăn",
        link: "BlogTayTrangRangBlog1",
        tab: "t4",
    },
    {
        id: 9,
        img: "images/rang-toan-su.jpg",
        service: "Điều Trị Tuỷ",
        title: "Khắc phục tình trạng đen viền nướu sau khi bọc răng sứ",
        discrip: "Bọc răng sứ được coi là phương pháp xuất hiện từ rất sớm. Phương pháp giúp khắc phục tình trạng răng bị mẻ, thưa, nhiễm màu kháng sinh nặng. Sau khi phục hình, răng mới sẽ trắng bóng tự nhiên. Tuy nhiên, thông tin về trường hợp bọc răng sứ bị đen viền nướu lại...",
        link: "BlogTayTrangRangBlog1",
        tab: "t5",
    },
]